export const ANGULAR_COMPONENTS_QUESTIONS = [
  { id: 1, question: 'What is the purpose of event-binding in Angular?', options: [], answer: '' },
  { id: 2, question: 'How does property-binding differ from event-binding?', options: [], answer: '' },
  { id: 3, question: 'What is the role of @Input() in Angular components?', options: [], answer: '' },
  { id: 4, question: 'How does @Output() facilitate communication between components?', options: [], answer: '' },
  { id: 5, question: 'What is view encapsulation in Angular, and why is it useful?', options: [], answer: '' },
  { id: 6, question: 'Describe the Angular component lifecycle and its phases.', options: [], answer: '' },
  { id: 7, question: 'How do you conditionally render pages using *ngIf?', options: [], answer: '' },
  { id: 8, question: 'What is the purpose of the `onSelectPage` function in navigation?', options: [], answer: '' },
  { id: 9, question: 'How do you use event-binding to listen for custom events in Angular?', options: [], answer: '' },
  { id: 10, question: 'Explain the role of the `currentPage` EventEmitter in navigation.', options: [], answer: '' },
  { id: 11, question: 'What is the purpose of the `pageDisplayed` variable in app.component?', options: [], answer: '' },
  { id: 12, question: 'How do you bind data to a component using property-binding?', options: [], answer: '' },
  { id: 13, question: 'What is the significance of using an @Input() decorator in a component?', options: [], answer: '' },
  { id: 14, question: 'Describe how to pass data from a parent component to a child component.', options: [], answer: '' },
  { id: 15, question: 'How can you handle book selection in a book-list component?', options: [], answer: '' },
  { id: 16, question: 'What is the purpose of using ng-template in Angular templates?', options: [], answer: '' },
  { id: 17, question: 'How does the `onBookSelected` method work in the book component?', options: [], answer: '' },
  { id: 18, question: 'What is the role of the `selectedBook` variable in the bookshelf component?', options: [], answer: '' },
  { id: 19, question: 'How can you display a list of books conditionally based on selection?', options: [], answer: '' },
  { id: 20, question: 'What is the purpose of `ngOnChanges` lifecycle hook in Angular?', options: [], answer: '' },
  { id: 21, question: 'Describe how the `ngAfterViewInit` lifecycle hook is used in Angular.', options: [], answer: '' },
  { id: 22, question: 'How does the `ngOnDestroy` lifecycle hook help manage resources?', options: [], answer: '' },
  { id: 23, question: 'What is the function of the `book` variable in the `book-details` component?', options: [], answer: '' },
  { id: 24, question: 'How can you use the `*ngIf` directive to conditionally display a component?', options: [], answer: '' },
  { id: 25, question: 'Explain the use of `EventEmitter` in the communication between Angular components.', options: [], answer: '' }
];
