export const ANGULAR_PROJECT_BASICS_QUESTIONS = [
  { id: 1, question: 'What is the purpose of planning an application before starting development?', options: [], answer: '' },
  { id: 2, question: 'Why is it important to create an intuitive folder structure in a project?', options: [], answer: '' },
  { id: 3, question: 'What is the role of Bootstrap in creating a navigation bar?', options: [], answer: '' },
  { id: 4, question: 'How do you create a model in Angular?', options: [], answer: '' },
  { id: 5, question: 'What is the purpose of using the Angular CLI?', options: [], answer: '' },
  { id: 6, question: 'How can you add components to an Angular project using the CLI?', options: [], answer: '' },
  { id: 7, question: 'What is the significance of adding Bootstrap styles to an Angular project?', options: [], answer: '' },
  { id: 8, question: 'How do you verify that Bootstrap is working in your Angular project?', options: [], answer: '' },
  { id: 9, question: 'What does the `<app-navigation>` component do in the application?', options: [], answer: '' },
  { id: 10, question: 'How do you display multiple components on a single page in Angular?', options: [], answer: '' },
  { id: 11, question: 'What are the core components of the Bookshelf feature?', options: [], answer: '' },
  { id: 12, question: 'What are the core components of the Library feature?', options: [], answer: '' },
  { id: 13, question: 'How do you add dummy data to a component in Angular?', options: [], answer: '' },
  { id: 14, question: 'What is the purpose of using `*ngFor` in Angular templates?', options: [], answer: '' },
  { id: 15, question: 'How do you bind a component property to an HTML element?', options: [], answer: '' },
  { id: 16, question: 'What is the purpose of the `Book` model in this application?', options: [], answer: '' },
  { id: 17, question: 'How do you use the `Book` model in different components?', options: [], answer: '' },
  { id: 18, question: 'What steps are involved in creating a book details component?', options: [], answer: '' },
  { id: 19, question: 'How do you style a navigation bar using Bootstrap?', options: [], answer: '' },
  { id: 20, question: 'What is the purpose of the `collapsed` and `show` variables in the navigation component?', options: [], answer: '' },
  { id: 21, question: 'How do you handle routing in Angular applications?', options: [], answer: '' },
  { id: 22, question: 'What are some common Bootstrap classes used for layout?', options: [], answer: '' },
  { id: 23, question: 'How do you add Google Fonts to an Angular project?', options: [], answer: '' },
  { id: 24, question: 'What are the advantages of using SCSS over plain CSS?', options: [], answer: '' },
  { id: 25, question: 'How do you debug an Angular application effectively?', options: [], answer: '' }
];
